### ISSUE TITLE
Reducing the multiupload.gif file

### ISSUE THREAD

**Issue by tifabien** [silasjoisten/sonata-multiupload-bundle#14]
Hi,

I would like to know whether it was possible to reduce the size of the multiupload.gif file or maybe move this file on a CDN as the bundle is taking ~8MB because of the size of this file?

Btw thanks a lot for your bundle it improves the usage of the upload process a lot!

**Comment by silasjoisten** [comment]
Hello @tifabien 

this idea sounds really good i will improve it.

**Comment by OskarStark** [comment]
You can keep it but you should ignore it while tagging (.gitexport config)

**Comment by silasjoisten** [comment]
Released in [2.0.1](https://github.com/silasjoisten/sonata-multiupload-bundle/releases/tag/2.0.1)
