### ISSUE TITLE
Add russian translation

### ISSUE THREAD

**Issue by silasjoisten** [silasjoisten/sonata-multiupload-bundle#26]
Would be great if someone could add translation in russian.

**Comment by malikzh** [comment]
Hi! I can help you with translation into Russian. What do you need to translate?

**Comment by silasjoisten** [comment]
You can translate 
https://github.com/silasjoisten/sonata-multiupload-bundle/blob/master/src/Resources/translations/SonataMultiUploadBundle.en.yml
