### ISSUE TITLE
Return to the media list onComplete

### ISSUE THREAD

**Issue by foucdeg** [silasjoisten/sonata-multiupload-bundle#35]
Hello,

A nice feature for this bundle would be an option so that the user is automatically redirected to the media list when all uploads are complete.
This could be done using the `onComplete` callback in `dmFileUploader`, in `multi_upload.hml.twig`.

What do you think? Should I open a pull request?

**Comment by silasjoisten** [comment]
Hi @foucdeg ,
sounds good for me, if you want you can do this but it should be configurable. 
Maybe like `redirect_to_list_on_success: true # false`. If you have a better name take it 😄

**Comment by silasjoisten** [comment]
Hi @foucdeg sorry for long waiting. I was verry buisy. I created a config option where you can configure the route you want to get redirected. Its called `redirect_to`.
