### ISSUE TITLE
Could not upload file in Gallery (Sonata Media Bundle) 

### ISSUE THREAD

**Issue by kmaci** [silasjoisten/sonata-multiupload-bundle#38]
Hi, 

I'm not able to upload images via multiupload form when I'm adding images to gallery
![vyber_523](https://user-images.githubusercontent.com/3668203/44841193-1468d100-ac43-11e8-8085-aa25a0d28ba3.png)

If I click on Add new in Gallery item row, I got Upload complete but in console, there is this error and image is not uploaded.
![vyber_525](https://user-images.githubusercontent.com/3668203/44841333-67db1f00-ac43-11e8-842a-53852ffc614a.png)

When I upload file via Media page, everything is fine.

**Comment by silasjoisten** [comment]
@kmaci The problem is That in Gallery you don't create Media directly. You are creating galleryHasMedias and its oneToMany related to Media. so it is not possible you

**Comment by silasjoisten** [comment]
Gallery <-> (ManyToOne) GalleryHasMedia <-> (OneToMany) Media

**Comment by silasjoisten** [comment]
That means that this isn't an issue related to this Bundle

**Comment by bugallos** [comment]
Hi,
@kmaci 
I found that it is possible to insert multiple media files and set gallery for them. Slightly code modification is needed.
Insert files with multiupload as always, but I added a gallery select-dropdown menu below. You can choose existing gallery from there (I don't know if it is possible to make creation of new gallery from that place, cause this isn't a regular Admin page connected to Entity). When uploading files, a GalleryHasMedia is created, so files are connected with gallery.

If you are interested, I can do Fork or just insert code snippets for you.

Screenshot: 
![multiupload-added-gallery](https://user-images.githubusercontent.com/28923651/48766765-7589c900-ecb5-11e8-967c-56f728f1847c.PNG)

**Comment by silasjoisten** [comment]
@kmaci , @bugallos If the #35 issue is finnished. than you'll be able to redirect directly to media list/grid.
On this place you can create a batch action for creating galleries.

**Comment by silasjoisten** [comment]
@kmaci @bugallos this issue is done you can create now an action which creates gallery from uploaded medias. configure this bundle via `redirect_to` option. It will automatically pass the ids from uploaded medias into the url. Take a look at the Documentation under Hints.
