### ISSUE TITLE
Cannot autowire service

### ISSUE THREAD

**Issue by khushal7764** [silasjoisten/sonata-multiupload-bundle#58]
Cannot autowire service "App\Controller\MediaAdminController": argument "$mediaManager" of method "SilasJoisten\Sonata\MultiUploadBundle\Controller\MultiUploadController::__construct()" references interface "Sonata\Doctrine\Model\ManagerInterface" but no such service exists. You should maybe alias this interface to one of these existing services: "sonata.media.manager.media", "sonata.media.manager.gallery".

**Comment by silasjoisten** [comment]
Sorry for the delay. 

Have you created an alias for the MediaManager?

**Comment by silasjoisten** [comment]
@khushal7764 anything on this?
