### ISSUE TITLE
Is there any way to define the min/max width-height and orientation requirements?

### ISSUE THREAD

**Issue by Lelya** [silasjoisten/sonata-multiupload-bundle#64]
Great extension! Thanks! 
Any question.
1. Is there any way to define the min/max width-height and orientation requirements for images? Is it possible to add a validate call to the my provider ?

`<?php

namespace Application\Sonata\MediaBundle\Provider;

final class PosterProvider extends ImageProvider
{
    use MultiUploadTrait;

    public function getProviderMetadata()
    {
        return new Metadata($this->getName(),
            $this->getName().'.description',
            false,
            'SonataMediaBundle',
            ['class' => 'fa fa-picture-o']
        );
    }
`

2. When adding a new media, how can I immediately go to upload without selecting a provider?

**Comment by silasjoisten** [comment]
Hi @Lelya,
1. you want to know if an image is landscape or horizontal? With the validate i am not sure. i guess there is a way but i need to take a deeper look on sonatamedia bundle
2. If you already know your provider you can generate the Url pointing directly to provider
```php
$this->sonataMediaAdmin->generateUrl('create', ['provider' => 'sonata.media.provider.image'])
```
 pass the provider to the url

**Comment by Lelya** [comment]
@silasjoisten, thank you for your answer! 
1. If it is not possible to determine whether the image is landscape or horizontal, then maybe you know how to determine the requirements for min / max width-height?

**Comment by Lelya** [comment]
2. I'm junior. Where exactly should I call this function
`$ this -> sonataMediaAdmin -> generateUrl ( ' create ' , [ ' provider '  =>  ' sonata.media.provider.image ' ])`

**Comment by silasjoisten** [comment]
> 1. If it is not possible to determine whether the image is landscape or horizontal, then maybe you know how to determine the requirements for min / max width-height?

I know there is a way but this would be related to SonataMediaBundle maybe ask in Slack Channel of sonata after this topic

**Comment by silasjoisten** [comment]
> 1. I'm junior. Where exactly should I call this function
>    `$ this -> sonataMediaAdmin -> generateUrl ( ' create ' , [ ' provider '  =>  ' sonata.media.provider.image ' ])`

This was just an example how to generate an url pointing directly to the multi upload
Every thing you need to do is passing `provider` in the `create` route of MediaAdmin

i dont know where do you want to generate this URL? in Twig template or in PHP code? you can use the snippet in controller or in any php class (Service). Preferences: You need to inject media admin into this service/controller
