### ISSUE TITLE
Update with recent sonata version, drop requirement of "sonata-project/core-bundle"

### ISSUE THREAD

**Issue by mpoiriert** [silasjoisten/sonata-multiupload-bundle#70]
I want to use this bundle but the newest version of sonata-project is incompatible with the core-bundle.

Do you plan to update this bundle or if you don't and we do it can we make a PR ? It will need a major release.

And before we do this can you confirm that it's a good solution for multi-upload in sonata or you think something else could be better ?

**Comment by silasjoisten** [comment]
Hi yea i plan to update this bundle i will take care of it.

**Comment by silasjoisten** [comment]
@mpoiriert Thank you for reporting that. Changes are in latest release!
